# Generated by Django 4.2.3 on 2023-07-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('salary', models.DecimalField(decimal_places=4, max_digits=16)),
                ('join_dt', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
